/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhmt.tuan3;

/**
 *
 * @author MSI GP72
 */
public class Calculator extends javax.swing.JFrame {
    private String pheptoan="";
    private long a = 0;


    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelCha = new javax.swing.JPanel();
        HienThi = new javax.swing.JLabel();
        CacNutAn = new javax.swing.JPanel();
        So1 = new javax.swing.JButton();
        So2 = new javax.swing.JButton();
        So3 = new javax.swing.JButton();
        Chia = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        So4 = new javax.swing.JButton();
        So5 = new javax.swing.JButton();
        So6 = new javax.swing.JButton();
        Nhan = new javax.swing.JButton();
        Phantram = new javax.swing.JButton();
        So7 = new javax.swing.JButton();
        So8 = new javax.swing.JButton();
        So9 = new javax.swing.JButton();
        Tru = new javax.swing.JButton();
        Motphanx = new javax.swing.JButton();
        So0 = new javax.swing.JButton();
        Congtru = new javax.swing.JButton();
        C = new javax.swing.JButton();
        Cong = new javax.swing.JButton();
        Bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        JPanelCha.setLayout(new java.awt.BorderLayout());

        HienThi.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        HienThi.setText("0");
        JPanelCha.add(HienThi, java.awt.BorderLayout.PAGE_START);

        CacNutAn.setLayout(new java.awt.GridLayout(4, 5));

        So1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So1.setText("1");
        So1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So1ActionPerformed(evt);
            }
        });
        CacNutAn.add(So1);

        So2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So2.setText("2");
        So2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So2ActionPerformed(evt);
            }
        });
        CacNutAn.add(So2);

        So3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So3.setText("3");
        So3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So3ActionPerformed(evt);
            }
        });
        CacNutAn.add(So3);

        Chia.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Chia.setText("/");
        Chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiaActionPerformed(evt);
            }
        });
        CacNutAn.add(Chia);

        sqrt.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        sqrt.setText("sqrt");
        CacNutAn.add(sqrt);

        So4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So4.setText("4");
        So4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So4ActionPerformed(evt);
            }
        });
        CacNutAn.add(So4);

        So5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So5.setText("5");
        So5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So5ActionPerformed(evt);
            }
        });
        CacNutAn.add(So5);

        So6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So6.setText("6");
        So6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So6ActionPerformed(evt);
            }
        });
        CacNutAn.add(So6);

        Nhan.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Nhan.setText("*");
        Nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanActionPerformed(evt);
            }
        });
        CacNutAn.add(Nhan);

        Phantram.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Phantram.setText("%");
        CacNutAn.add(Phantram);

        So7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So7.setText("7");
        So7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So7ActionPerformed(evt);
            }
        });
        CacNutAn.add(So7);

        So8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So8.setText("8");
        So8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So8ActionPerformed(evt);
            }
        });
        CacNutAn.add(So8);

        So9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So9.setText("9");
        So9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So9ActionPerformed(evt);
            }
        });
        CacNutAn.add(So9);

        Tru.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Tru.setText("-");
        Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruActionPerformed(evt);
            }
        });
        CacNutAn.add(Tru);

        Motphanx.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Motphanx.setText("1/x");
        CacNutAn.add(Motphanx);

        So0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        So0.setText("0");
        So0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So0ActionPerformed(evt);
            }
        });
        CacNutAn.add(So0);

        Congtru.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Congtru.setText("+/-");
        CacNutAn.add(Congtru);

        C.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        C.setText("C");
        CacNutAn.add(C);

        Cong.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Cong.setText("+");
        Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CongActionPerformed(evt);
            }
        });
        CacNutAn.add(Cong);

        Bang.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Bang.setText("=");
        CacNutAn.add(Bang);

        JPanelCha.add(CacNutAn, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCha, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void So1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So1ActionPerformed
      String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So1.getText());
      this.HienThi.setText(String.valueOf(so));
      }// TODO add your handling code here:
    }//GEN-LAST:event_So1ActionPerformed

    private void So2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So2ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So2.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So2ActionPerformed

    private void So3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So3ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So3.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So3ActionPerformed

    private void So4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So4ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So4.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So4ActionPerformed

    private void So5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So5ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So5.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So5ActionPerformed

    private void So6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So6ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So6.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So6ActionPerformed

    private void So7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So7ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So7.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So7ActionPerformed

    private void So8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So8ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So8.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So8ActionPerformed

    private void So9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So9ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So9.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So9ActionPerformed

    private void So0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So0ActionPerformed
String gt=this.HienThi.getText();
      if (gt.length()<12){
      if (gt.equals("0")) gt="";
      long so = Long.parseLong(gt + So0.getText());
      this.HienThi.setText(String.valueOf(so));
      }        // TODO add your handling code here:
    }//GEN-LAST:event_So0ActionPerformed

    private void ChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiaActionPerformed
this.a = Long.parseLong(this.HienThi.getText());
if (this.a !=0){
this.pheptoan = "/";
this.HienThi.setText("0");
}// TODO add your handling code here:
    }//GEN-LAST:event_ChiaActionPerformed

    private void NhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanActionPerformed
this.a = Long.parseLong(this.HienThi.getText());
this.pheptoan = "*";
this.HienThi.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_NhanActionPerformed

    private void TruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruActionPerformed
this.a = Long.parseLong(this.HienThi.getText());
this.pheptoan = "-";
this.HienThi.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_TruActionPerformed

    private void CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CongActionPerformed
this.a = Long.parseLong(this.HienThi.getText());
this.pheptoan = "+";
this.HienThi.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_CongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bang;
    private javax.swing.JButton C;
    private javax.swing.JPanel CacNutAn;
    private javax.swing.JButton Chia;
    private javax.swing.JButton Cong;
    private javax.swing.JButton Congtru;
    private javax.swing.JLabel HienThi;
    private javax.swing.JPanel JPanelCha;
    private javax.swing.JButton Motphanx;
    private javax.swing.JButton Nhan;
    private javax.swing.JButton Phantram;
    private javax.swing.JButton So0;
    private javax.swing.JButton So1;
    private javax.swing.JButton So2;
    private javax.swing.JButton So3;
    private javax.swing.JButton So4;
    private javax.swing.JButton So5;
    private javax.swing.JButton So6;
    private javax.swing.JButton So7;
    private javax.swing.JButton So8;
    private javax.swing.JButton So9;
    private javax.swing.JButton Tru;
    private javax.swing.JButton sqrt;
    // End of variables declaration//GEN-END:variables
}
