/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhmt.tuan3;

import javax.swing.JOptionPane;

/**
 *
 * @author MSI GP72
 */
public class DemoTroChoi extends javax.swing.JFrame {

    /**
     * Creates new form DemoTroChoi
     */
    public DemoTroChoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCha = new javax.swing.JPanel();
        Jpaneltren = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDuoi = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelGiua = new javax.swing.JPanel();
        so15 = new javax.swing.JButton();
        so14 = new javax.swing.JButton();
        so13 = new javax.swing.JButton();
        so12 = new javax.swing.JButton();
        so11 = new javax.swing.JButton();
        so10 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so1 = new javax.swing.JButton();
        empty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trò Chơi");

        jPanelCha.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(172, 218, 126));
        jLabel1.setText("Trò Chơi Xếp Số");
        Jpaneltren.add(jLabel1);

        jPanelCha.add(Jpaneltren, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Bắt Đầu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelDuoi.add(jButton1);

        jPanelCha.add(jPanelDuoi, java.awt.BorderLayout.PAGE_END);

        jPanelGiua.setLayout(new java.awt.GridLayout(4, 4));

        so15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so15.setText("15");
        so15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so15ActionPerformed(evt);
            }
        });
        jPanelGiua.add(so15);

        so14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so14.setText("14");
        so14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so14ActionPerformed(evt);
            }
        });
        jPanelGiua.add(so14);

        so13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so13.setText("13");
        jPanelGiua.add(so13);

        so12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so12.setText("12");
        jPanelGiua.add(so12);

        so11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so11.setText("11");
        jPanelGiua.add(so11);

        so10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so10.setText("10");
        jPanelGiua.add(so10);

        so9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so9.setText("9");
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so9ActionPerformed(evt);
            }
        });
        jPanelGiua.add(so9);

        so8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so8.setText("8");
        jPanelGiua.add(so8);

        so7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so7.setText("7");
        jPanelGiua.add(so7);

        so6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so6.setText("6");
        jPanelGiua.add(so6);

        so5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so5.setText("5");
        jPanelGiua.add(so5);

        so4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so4.setText("4");
        jPanelGiua.add(so4);

        so3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so3.setText("3");
        jPanelGiua.add(so3);

        so2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so2.setText("2");
        jPanelGiua.add(so2);

        so1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        so1.setText("1");
        jPanelGiua.add(so1);
        jPanelGiua.add(empty);

        jPanelCha.add(jPanelGiua, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCha, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCha, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog("Họ và tên");
        this.setTitle("Trò chơi xếp ô số");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void so14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_so14ActionPerformed

    private void so9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_so9ActionPerformed

    private void so15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_so15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoTroChoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoTroChoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoTroChoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoTroChoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoTroChoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpaneltren;
    private javax.swing.JButton empty;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCha;
    private javax.swing.JPanel jPanelDuoi;
    private javax.swing.JPanel jPanelGiua;
    private javax.swing.JButton so1;
    private javax.swing.JButton so10;
    private javax.swing.JButton so11;
    private javax.swing.JButton so12;
    private javax.swing.JButton so13;
    private javax.swing.JButton so14;
    private javax.swing.JButton so15;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    // End of variables declaration//GEN-END:variables
}
