/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhmt.tuan3;

/**
 *
 * @author MSI GP72
 */
public class QuanLySanPham extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySanPham
     */
    public QuanLySanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCha = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanelBot = new javax.swing.JPanel();
        jPanelMiddle = new javax.swing.JPanel();
        DanhMuc = new javax.swing.JPanel();
        PanelChon = new javax.swing.JPanel();
        New = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        List = new javax.swing.JScrollPane();
        ListDoa = new javax.swing.JList<>();
        ThongTinsanpham = new javax.swing.JPanel();
        jPanelTop1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        jPanelBot1 = new javax.swing.JPanel();
        jPanelMiddle1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sản Phẩm");

        LbCha.setLayout(new java.awt.BorderLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 0, 204));
        Title.setText("Quản Lý Sản Phẩm");
        jPanelTop.add(Title);

        LbCha.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        LbCha.add(jPanelBot, java.awt.BorderLayout.PAGE_END);

        DanhMuc.setLayout(new java.awt.BorderLayout());

        New.setText("New");

        Update.setText("Update");

        Remove.setText("Remove");

        javax.swing.GroupLayout PanelChonLayout = new javax.swing.GroupLayout(PanelChon);
        PanelChon.setLayout(PanelChonLayout);
        PanelChonLayout.setHorizontalGroup(
            PanelChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelChonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remove)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelChonLayout.setVerticalGroup(
            PanelChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelChonLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New)
                    .addComponent(Update)
                    .addComponent(Remove))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        DanhMuc.add(PanelChon, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh mục sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        ListDoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ListDoa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Đào loại 1", "Đào loại 2", "Đào loại 3", "Đào loại 4", "Đào loại 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        List.setViewportView(ListDoa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        DanhMuc.add(jPanel2, java.awt.BorderLayout.CENTER);

        ThongTinsanpham.setLayout(new java.awt.BorderLayout());

        Title1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Title1.setText("Thông tin chi tiết");
        jPanelTop1.add(Title1);

        ThongTinsanpham.add(jPanelTop1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanelBot1Layout = new javax.swing.GroupLayout(jPanelBot1);
        jPanelBot1.setLayout(jPanelBot1Layout);
        jPanelBot1Layout.setHorizontalGroup(
            jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        jPanelBot1Layout.setVerticalGroup(
            jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ThongTinsanpham.add(jPanelBot1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanelMiddle1Layout = new javax.swing.GroupLayout(jPanelMiddle1);
        jPanelMiddle1.setLayout(jPanelMiddle1Layout);
        jPanelMiddle1Layout.setHorizontalGroup(
            jPanelMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        jPanelMiddle1Layout.setVerticalGroup(
            jPanelMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        ThongTinsanpham.add(jPanelMiddle1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelMiddleLayout = new javax.swing.GroupLayout(jPanelMiddle);
        jPanelMiddle.setLayout(jPanelMiddleLayout);
        jPanelMiddleLayout.setHorizontalGroup(
            jPanelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiddleLayout.createSequentialGroup()
                .addComponent(DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongTinsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelMiddleLayout.setVerticalGroup(
            jPanelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ThongTinsanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LbCha.add(jPanelMiddle, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbCha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbCha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DanhMuc;
    private javax.swing.JPanel LbCha;
    private javax.swing.JScrollPane List;
    private javax.swing.JList<String> ListDoa;
    private javax.swing.JButton New;
    private javax.swing.JPanel PanelChon;
    private javax.swing.JButton Remove;
    private javax.swing.JPanel ThongTinsanpham;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton Update;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelBot1;
    private javax.swing.JPanel jPanelMiddle;
    private javax.swing.JPanel jPanelMiddle1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTop1;
    // End of variables declaration//GEN-END:variables
}
