/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhmt.tuan3;

/**
 *
 * @author MSI GP72
 */
public class Tinhtoan extends javax.swing.JFrame {

    /**
     * Creates new form Tinhtoan
     */
    public Tinhtoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nhomcheck = new javax.swing.ButtonGroup();
        JpnRoot = new javax.swing.JPanel();
        JpnTop = new javax.swing.JPanel();
        LbTieuDe = new javax.swing.JLabel();
        LbBot = new javax.swing.JPanel();
        LbMiddle = new javax.swing.JPanel();
        Lbgiua = new javax.swing.JPanel();
        LbTacVu = new javax.swing.JPanel();
        Giai = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        LbNhapab = new javax.swing.JPanel();
        nhapab = new javax.swing.JPanel();
        Chodenhapa = new javax.swing.JTextField();
        Chodenhapb = new javax.swing.JTextField();
        nhapa = new java.awt.Label();
        nhapb = new java.awt.Label();
        LbChon = new javax.swing.JPanel();
        Cong = new javax.swing.JRadioButton();
        Tru = new javax.swing.JRadioButton();
        Nhan = new javax.swing.JRadioButton();
        Chia = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cộng - Trừ - Nhân - Chia");

        JpnRoot.setLayout(new java.awt.BorderLayout());

        LbTieuDe.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LbTieuDe.setForeground(new java.awt.Color(255, 51, 51));
        LbTieuDe.setText("Cộng Trừ Nhân Chia");
        JpnTop.add(LbTieuDe);

        JpnRoot.add(JpnTop, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout LbBotLayout = new javax.swing.GroupLayout(LbBot);
        LbBot.setLayout(LbBotLayout);
        LbBotLayout.setHorizontalGroup(
            LbBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        LbBotLayout.setVerticalGroup(
            LbBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JpnRoot.add(LbBot, java.awt.BorderLayout.PAGE_END);

        LbMiddle.setLayout(new javax.swing.BoxLayout(LbMiddle, javax.swing.BoxLayout.LINE_AXIS));

        LbTacVu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        Giai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Giai.setText("Giải");

        Xoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Thoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Thoat.setText("Thoát");

        javax.swing.GroupLayout LbTacVuLayout = new javax.swing.GroupLayout(LbTacVu);
        LbTacVu.setLayout(LbTacVuLayout);
        LbTacVuLayout.setHorizontalGroup(
            LbTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LbTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LbTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LbTacVuLayout.createSequentialGroup()
                        .addComponent(Thoat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Giai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LbTacVuLayout.setVerticalGroup(
            LbTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Giai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Xoa)
                .addGap(13, 13, 13)
                .addComponent(Thoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LbNhapab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập 2 số a và b", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        Chodenhapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChodenhapaActionPerformed(evt);
            }
        });

        nhapa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nhapa.setText("Nhập a");

        nhapb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nhapb.setText("Nhập b");

        LbChon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phép Toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        Nhomcheck.add(Cong);
        Cong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Cong.setText("Cộng");

        Nhomcheck.add(Tru);
        Tru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tru.setText("Trừ");

        Nhomcheck.add(Nhan);
        Nhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Nhan.setText("Nhân");

        Nhomcheck.add(Chia);
        Chia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Chia.setText("Chia");
        Chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LbChonLayout = new javax.swing.GroupLayout(LbChon);
        LbChon.setLayout(LbChonLayout);
        LbChonLayout.setHorizontalGroup(
            LbChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbChonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LbChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nhan)
                    .addComponent(Cong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(LbChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chia)
                    .addComponent(Tru))
                .addContainerGap())
        );
        LbChonLayout.setVerticalGroup(
            LbChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbChonLayout.createSequentialGroup()
                .addGroup(LbChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cong)
                    .addComponent(Tru))
                .addGap(18, 18, 18)
                .addGroup(LbChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nhan)
                    .addComponent(Chia))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Kết quả");

        javax.swing.GroupLayout nhapabLayout = new javax.swing.GroupLayout(nhapab);
        nhapab.setLayout(nhapabLayout);
        nhapabLayout.setHorizontalGroup(
            nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhapabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chodenhapb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nhapabLayout.createSequentialGroup()
                        .addComponent(LbChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addComponent(Chodenhapa)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        nhapabLayout.setVerticalGroup(
            nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhapabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Chodenhapa, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(nhapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Chodenhapb, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(nhapb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout LbNhapabLayout = new javax.swing.GroupLayout(LbNhapab);
        LbNhapab.setLayout(LbNhapabLayout);
        LbNhapabLayout.setHorizontalGroup(
            LbNhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbNhapabLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(nhapab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        LbNhapabLayout.setVerticalGroup(
            LbNhapabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbNhapabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nhapab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LbgiuaLayout = new javax.swing.GroupLayout(Lbgiua);
        Lbgiua.setLayout(LbgiuaLayout);
        LbgiuaLayout.setHorizontalGroup(
            LbgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbgiuaLayout.createSequentialGroup()
                .addComponent(LbTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbNhapab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LbgiuaLayout.setVerticalGroup(
            LbgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LbgiuaLayout.createSequentialGroup()
                .addGroup(LbgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbNhapab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        LbMiddle.add(Lbgiua);

        JpnRoot.add(LbMiddle, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XoaActionPerformed

    private void ChodenhapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChodenhapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChodenhapaActionPerformed

    private void ChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChiaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tinhtoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Chia;
    private javax.swing.JTextField Chodenhapa;
    private javax.swing.JTextField Chodenhapb;
    private javax.swing.JRadioButton Cong;
    private javax.swing.JButton Giai;
    private javax.swing.JPanel JpnRoot;
    private javax.swing.JPanel JpnTop;
    private javax.swing.JPanel LbBot;
    private javax.swing.JPanel LbChon;
    private javax.swing.JPanel LbMiddle;
    private javax.swing.JPanel LbNhapab;
    private javax.swing.JPanel LbTacVu;
    private javax.swing.JLabel LbTieuDe;
    private javax.swing.JPanel Lbgiua;
    private javax.swing.JRadioButton Nhan;
    private javax.swing.ButtonGroup Nhomcheck;
    private javax.swing.JButton Thoat;
    private javax.swing.JRadioButton Tru;
    private javax.swing.JButton Xoa;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label nhapa;
    private javax.swing.JPanel nhapab;
    private java.awt.Label nhapb;
    // End of variables declaration//GEN-END:variables
}
